name: Branchyng Strategy DEV
on:
  workflow_dispatch:
  pull_request:
    types: [ assigned, opened, synchronize ]
    branches:
      - dev/*
env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
  CELULA: ${{ secrets.CELULA }}
jobs:
  Branching-Fork:
    name: Branching-Fork
    uses: branching-strategy-brian/DevOps-Workflow/.github/workflows/dev.yml@main
    with: 
      environment: 'dev/${{ env.TOKEN }}