name: Branchyng Strategy DEV
on:
  pull_request:
    types: [ assigned, opened, synchronize ]
    branches:
      - dev/*
  workflow_dispatch:
jobs:
  Current-Branch:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_HEAD_REF#refs/heads/})"
        id: extract_branch
      - uses: jungwinter/split@v2
        id: split
        with:
          msg: '${{ steps.extract_branch.outputs.branch }}'
          separator: '/'
    outputs: 
      branch: ${{ steps.extract_branch.outputs.branch }}
      team: ${{ steps.split.outputs._1 }}
      env: ${{ steps.split.outputs._0 }}
  Branching-Fork:
    name: Branching-Fork
    needs: Current-Branch
    uses: branching-strategy-brian/DevOps-Workflow/.github/workflows/dev.yml@${{needs.Current-Branch.outputs.team}}
    with: 
      environment: dev/${{needs.Current-Branch.outputs.team}}
    secrets:
      TOKEN: ${{ secrets.TOKEN }}