name: Branchyng Strategy DEV
on:
  pull_request:
    types: [ assigned, opened, synchronize ]
    branches:
      - dev/*
  workflow_dispatch:
jobs:
  Branching-Fork:
    name: Branching-Fork
    needs: Current-Branch
    uses: branching-strategy-brian/DevOps-Workflow/.github/workflows/dev.yml@main