name: Branchyng Strategy DEV
on:
  pull_request:
    types: [ assigned, opened, synchronize ]
    branches:
      - dev/*

jobs:
  build:
  uses:
    branching-strategy-brian/DevOps-Workflow/.github/workflows/dev.yml@main