name: Branchyng Strategy PRE
on:
  pull_request:
    types: [ assigned, opened, synchronize ]
    branches:
      - preproduccion/*

jobs:
  build:
  uses:
    branching-strategy-brian/DevOps-Workflow/.github/workflows/preproduccion.yml@main