name: Branchyng Strategy PRE
on:
  pull_request:
    types: [ assigned, opened, synchronize ]
    branches:
      - preproduccion/*
  workflow_dispatch:
jobs:
  Current-Branch:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Echo Extract branch name
        shell: bash
        run: echo ${{ steps.extract_branch.outputs.branch }}
      - name: Extract actor
        shell: bash
        run: echo "##[set-output name=actor;]$(echo ${GITHUB_ACTOR#refs/heads/})"
        id: extract_actor
      - name: Echo Extract actor name
        shell: bash
        run: echo ${{ steps.extract_actor.outputs.actor }}
      - uses: jungwinter/split@v2
        id: split
        with:
          msg: '${{ steps.extract_branch.outputs.branch }}'
          separator: '/'
    outputs: 
      branch: ${{ steps.extract_branch.outputs.branch }}
      team: ${{ steps.split.outputs._1 }}
      env: ${{ steps.split.outputs._0 }}
  Branching-Fork:
    name: Branching-Fork
    needs: Current-Branch
    uses: branching-strategy-brian/DevOps-Workflow/.github/workflows/preproduccion.yml@main
    with: 
      environment: preproduccion/${{needs.Current-Branch.outputs.team}}
    secrets:
      TOKEN: ${{ secrets.TOKEN }}