name: Branchyng Strategy QA
on:
  pull_request:
    types: [ assigned, opened, synchronize ]
    branches:
      - qa/*

jobs:
  build:
  uses:
    branching-strategy-brian/DevOps-Workflow/.github/workflows/qa.yml@main